# Generated by Django 5.1.3 on 2026-01-26 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0006_producto_costo_promedio_alter_producto_precio"),
        ("finanzas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("cliente", models.CharField(blank=True, max_length=120)),
                ("total_venta", models.PositiveIntegerField(default=0)),
                ("total_costo", models.PositiveIntegerField(default=0)),
                ("ganancia_total", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="VentaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("precio_unitario", models.PositiveIntegerField(default=0)),
                ("costo_unitario", models.PositiveIntegerField(default=0)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="crud.producto"
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finanzas.venta",
                    ),
                ),
            ],
        ),
    ]
