# Generated by Django 5.1.3 on 2026-01-26 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crud", "0006_producto_costo_promedio_alter_producto_precio"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("COMPRA", "Compra"), ("VENTA", "Venta")],
                        max_length=10,
                    ),
                ),
                ("referencia", models.CharField(blank=True, max_length=120)),
                ("nota", models.TextField(blank=True)),
                ("total", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="DetalleMovimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("precio_unitario", models.PositiveIntegerField()),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="crud.producto"
                    ),
                ),
                (
                    "movimiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="core.movimientoinventario",
                    ),
                ),
            ],
        ),
    ]
