# Generated by Django 6.0.5 on 2026-05-18 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('crud', '0018_movimientoinventario_imagenproducto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallemovimiento',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_movimiento_core', to='crud.producto'),
        ),
    ]
