# Generated by Django 5.2.3 on 2025-10-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_producto_oferta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
                ('calificacion', models.IntegerField(choices=[(1, '1 ★'), (2, '2 ★'), (3, '3 ★'), (4, '4 ★'), (5, '5 ★')], default=5)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
