# Generated by Django 5.2.3 on 2025-10-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_reseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseña',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=150),
            preserve_default=False,
        ),
    ]
