# Generated by Django 5.1.3 on 2026-01-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0005_reseña_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="costo_promedio",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.PositiveIntegerField(),
        ),
    ]
