# Generated by Django 5.1.3 on 2026-02-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0006_producto_costo_promedio_alter_producto_precio"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="destacado",
            field=models.BooleanField(default=False),
        ),
    ]
