# Generated by Django 5.1.3 on 2026-02-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0007_producto_destacado"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="super_oferta",
            field=models.BooleanField(default=False),
        ),
    ]
