# Generated by Django 5.1.3 on 2026-02-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0008_producto_super_oferta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="super_oferta",
            field=models.BooleanField(default=False, verbose_name="¿Es Super Oferta?"),
        ),
    ]
