# Generated by Django 5.1.3 on 2026-03-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0009_alter_producto_super_oferta"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producto",
            options={"ordering": ["orden", "id"]},
        ),
        migrations.AddField(
            model_name="producto",
            name="orden",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
