# Generated by Django 5.1.3 on 2026-03-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0010_alter_producto_options_producto_orden"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="orden_destacado",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
