# Generated by Django 5.1.3 on 2026-04-21 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0011_producto_orden_destacado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_documento", models.CharField(max_length=20, unique=True)),
                ("nombre_completo", models.CharField(max_length=150)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("BOLETA", "Boleta"), ("FACTURA", "Factura")],
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("total", models.PositiveIntegerField(default=0)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ventas",
                        to="crud.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetalleVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("precio_unitario", models.PositiveIntegerField()),
                ("subtotal", models.PositiveIntegerField(default=0)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_venta",
                        to="crud.producto",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="crud.venta",
                    ),
                ),
            ],
        ),
    ]
