# Generated by Django 5.1.3 on 2026-04-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0012_cliente_venta_detalleventa"),
    ]

    operations = [
        migrations.AddField(
            model_name="reseña",
            name="aprobada",
            field=models.BooleanField(default=False),
        ),
    ]
