# Generated by Django 5.1.3 on 2026-04-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0013_reseña_aprobada"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="nombre_completo",
        ),
        migrations.AddField(
            model_name="cliente",
            name="apellido",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="comuna",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="departamento",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="direccion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="informacion_adicional",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="nombre",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="numero",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="rut",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
