# Generated by Django 5.1.3 on 2026-05-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0014_remove_cliente_nombre_completo_cliente_apellido_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Informe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("descripcion", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Mejora", "Mejora"),
                            ("Reclamo", "Reclamo"),
                            ("Error del sistema", "Error del sistema"),
                            ("Problema de stock", "Problema de stock"),
                            ("Problema con cliente", "Problema con cliente"),
                            ("Problema con venta", "Problema con venta"),
                            ("Proveedor", "Proveedor"),
                            ("Otro", "Otro"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("Baja", "Baja"),
                            ("Media", "Media"),
                            ("Alta", "Alta"),
                        ],
                        default="Baja",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("En revisión", "En revisión"),
                            ("Resuelto", "Resuelto"),
                        ],
                        default="Pendiente",
                        max_length=20,
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-creado"],
            },
        ),
    ]
