# Generated by Django 5.1.3 on 2026-05-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0015_informe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suscriptor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
                ("marca", models.CharField(blank=True, max_length=50, null=True)),
                ("modelo", models.CharField(blank=True, max_length=50, null=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
