# Generated by Django 6.0.5 on 2026-05-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0018_movimientoinventario_imagenproducto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Calificación del producto de 0.0 a 5.0', max_digits=2),
        ),
    ]
